# Numpy Arrays

In [39]:
import numpy as np

In [40]:
mylist = [1,2,3]

In [41]:
type(mylist)

list

In [42]:
myarray = np.array(mylist)

In [43]:
type(myarray)

numpy.ndarray

In [44]:
myarray

array([1, 2, 3])

In [45]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [46]:
np.arange(0,10,0.5)

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. ,
       6.5, 7. , 7.5, 8. , 8.5, 9. , 9.5])

In [47]:
np.zeros(shape=(5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [48]:
np.ones(shape=(2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

## Operations

In [49]:
# Create the same random numbers each time through a seed
np.random.seed(101)
arr = np.random.randint(0,100,10)
arr

array([95, 11, 81, 70, 63, 87, 75,  9, 77, 40])

In [50]:
arr2 = np.random.randint(0,100,10)
arr2

array([ 4, 63, 40, 60, 92, 64,  5, 12, 93, 40])

In [51]:
# Max number in array
arr.max()

95

In [52]:
# Position (index) of the max number in array
arr.argmax()

0

In [53]:
# Min number in array
arr.min()

9

In [54]:
# Position (index) of the min number in array
arr.argmin()

7

In [55]:
# Calculate the average of all the values in array
arr.mean()

60.8

In [56]:
arr.shape

(10,)

In [57]:
# Reshape the array
arr.reshape((2,5))

array([[95, 11, 81, 70, 63],
       [87, 75,  9, 77, 40]])

## Indexing 

In [58]:
mat = np.arange(0,100).reshape(10,10)
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [59]:
row = 5
col = 1

In [60]:
mat[row,col]

51

## Slicing

In [61]:
mat[:,1]

array([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [62]:
mat[2,:]

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [63]:
mat[0:3,0:4]

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23]])

## Reassign

It can be useful to reassign some image pixels

In [64]:
mynewmat = mat.copy()
mynewmat[0:3,0:4] = 0
mynewmat

array([[ 0,  0,  0,  0,  4,  5,  6,  7,  8,  9],
       [ 0,  0,  0,  0, 14, 15, 16, 17, 18, 19],
       [ 0,  0,  0,  0, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])